apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet-fundamental-demo-deployment
spec:
  selector:
    matchLabels:
      app: aspnet-fundamental-demo
  template:
    metadata:
      labels:
        app: aspnet-fundamental-demo
    spec:
      containers:
      - name: aspnet-fundamental-demo
        image: kafkawannafly/web-api-demo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: MongoDbSettings__Host
            value: mongodb-service
          - name: MongoDbSettings__Password
            valueFrom:
              secretKeyRef:
                name: demo-secrets
                key: mongodb-password
        livenessProbe:
          httpGet:
            path: /hc/live
            port: 80
        readinessProbe:
          httpGet:
            path: /hc/ready
            port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: aspnet-fundamental-demo-service
spec:
  type: LoadBalancer
  selector:
    app: aspnet-fundamental-demo
  ports:
  - port: 80
    targetPort: 80

